{
 "title": "GravyTimescaleOutput Copy",
 "time": { "from": "2005-02-28T08:00:00.000Z", "to": "2011-02-17T08:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "run_timestamp", "label": "Run timstamp", "query": "1618175345" }
  ]
 },
 "panels": [
  {
   "title": "Portfolio Values",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  correlatedpairs_portfolio_value,\n  buyandhold_portfolio_value,\n  buyspy_portfolio_value\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Alpha",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  correlatedpairs_alpha_252,\n  buyandhold_alpha_252,\n  buyspy_alpha_252\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Beta",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  correlatedpairs_beta_252,\n  buyandhold_beta_252,\n  buyspy_beta_252\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}