// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: data/dailyprices/proto/daily_prices.proto

package dailyprices_pb

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *timestamp.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version   int32                `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_dailyprices_proto_daily_prices_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_data_dailyprices_proto_daily_prices_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_data_dailyprices_proto_daily_prices_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Request) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DailyPrices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StockPrices []*DailyPrices_StockPrices `protobuf:"bytes,1,rep,name=stock_prices,json=stockPrices,proto3" json:"stock_prices,omitempty"`
	Timestamp   *timestamp.Timestamp       `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version     int32                      `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *DailyPrices) Reset() {
	*x = DailyPrices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_dailyprices_proto_daily_prices_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyPrices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyPrices) ProtoMessage() {}

func (x *DailyPrices) ProtoReflect() protoreflect.Message {
	mi := &file_data_dailyprices_proto_daily_prices_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyPrices.ProtoReflect.Descriptor instead.
func (*DailyPrices) Descriptor() ([]byte, []int) {
	return file_data_dailyprices_proto_daily_prices_proto_rawDescGZIP(), []int{1}
}

func (x *DailyPrices) GetStockPrices() []*DailyPrices_StockPrices {
	if x != nil {
		return x.StockPrices
	}
	return nil
}

func (x *DailyPrices) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DailyPrices) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DailyPrices_StockPrices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker   string  `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Open     float64 `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	Close    float64 `protobuf:"fixed64,3,opt,name=close,proto3" json:"close,omitempty"`
	AdjClose float64 `protobuf:"fixed64,4,opt,name=adj_close,json=adjClose,proto3" json:"adj_close,omitempty"`
	Low      float64 `protobuf:"fixed64,5,opt,name=low,proto3" json:"low,omitempty"`
	High     float64 `protobuf:"fixed64,6,opt,name=high,proto3" json:"high,omitempty"`
	Volume   float64 `protobuf:"fixed64,7,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *DailyPrices_StockPrices) Reset() {
	*x = DailyPrices_StockPrices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_dailyprices_proto_daily_prices_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyPrices_StockPrices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyPrices_StockPrices) ProtoMessage() {}

func (x *DailyPrices_StockPrices) ProtoReflect() protoreflect.Message {
	mi := &file_data_dailyprices_proto_daily_prices_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyPrices_StockPrices.ProtoReflect.Descriptor instead.
func (*DailyPrices_StockPrices) Descriptor() ([]byte, []int) {
	return file_data_dailyprices_proto_daily_prices_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DailyPrices_StockPrices) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *DailyPrices_StockPrices) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *DailyPrices_StockPrices) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *DailyPrices_StockPrices) GetAdjClose() float64 {
	if x != nil {
		return x.AdjClose
	}
	return 0
}

func (x *DailyPrices_StockPrices) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *DailyPrices_StockPrices) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *DailyPrices_StockPrices) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

var File_data_dailyprices_proto_daily_prices_proto protoreflect.FileDescriptor

var file_data_dailyprices_proto_daily_prices_proto_rawDesc = []byte{
	0x0a, 0x29, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x5f, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x61, 0x69,
	0x6c, 0x79, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xd7, 0x02, 0x0a, 0x0b, 0x44, 0x61, 0x69,
	0x6c, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x47, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x63,
	0x6b, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x69,
	0x6c, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x0b, 0x73, 0x74, 0x6f, 0x63, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0xaa, 0x01, 0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x63, 0x6b, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6f, 0x70, 0x65,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x64, 0x6a, 0x5f, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x64, 0x6a, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x32, 0x3f, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x14, 0x2e, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x70, 0x72, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x73, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x64, 0x61, 0x69, 0x6c, 0x79, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_dailyprices_proto_daily_prices_proto_rawDescOnce sync.Once
	file_data_dailyprices_proto_daily_prices_proto_rawDescData = file_data_dailyprices_proto_daily_prices_proto_rawDesc
)

func file_data_dailyprices_proto_daily_prices_proto_rawDescGZIP() []byte {
	file_data_dailyprices_proto_daily_prices_proto_rawDescOnce.Do(func() {
		file_data_dailyprices_proto_daily_prices_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_dailyprices_proto_daily_prices_proto_rawDescData)
	})
	return file_data_dailyprices_proto_daily_prices_proto_rawDescData
}

var file_data_dailyprices_proto_daily_prices_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_dailyprices_proto_daily_prices_proto_goTypes = []interface{}{
	(*Request)(nil),                 // 0: dailyprices.Request
	(*DailyPrices)(nil),             // 1: dailyprices.DailyPrices
	(*DailyPrices_StockPrices)(nil), // 2: dailyprices.DailyPrices.StockPrices
	(*timestamp.Timestamp)(nil),     // 3: google.protobuf.Timestamp
}
var file_data_dailyprices_proto_daily_prices_proto_depIdxs = []int32{
	3, // 0: dailyprices.Request.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: dailyprices.DailyPrices.stock_prices:type_name -> dailyprices.DailyPrices.StockPrices
	3, // 2: dailyprices.DailyPrices.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: dailyprices.Data.Get:input_type -> dailyprices.Request
	1, // 4: dailyprices.Data.Get:output_type -> dailyprices.DailyPrices
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_data_dailyprices_proto_daily_prices_proto_init() }
func file_data_dailyprices_proto_daily_prices_proto_init() {
	if File_data_dailyprices_proto_daily_prices_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_dailyprices_proto_daily_prices_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_dailyprices_proto_daily_prices_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyPrices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_dailyprices_proto_daily_prices_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyPrices_StockPrices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_dailyprices_proto_daily_prices_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_dailyprices_proto_daily_prices_proto_goTypes,
		DependencyIndexes: file_data_dailyprices_proto_daily_prices_proto_depIdxs,
		MessageInfos:      file_data_dailyprices_proto_daily_prices_proto_msgTypes,
	}.Build()
	File_data_dailyprices_proto_daily_prices_proto = out.File
	file_data_dailyprices_proto_daily_prices_proto_rawDesc = nil
	file_data_dailyprices_proto_daily_prices_proto_goTypes = nil
	file_data_dailyprices_proto_daily_prices_proto_depIdxs = nil
}
