# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: supervisor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='supervisor.proto',
  package='supervisor',
  syntax='proto3',
  serialized_options=b'Z8github.com/d-sparks/gravy/supervisor/proto;supervisor_pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10supervisor.proto\x12\nsupervisor\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x0b\x41lgorithmId\x12\x14\n\x0c\x61lgorithm_id\x18\x01 \x01(\t\"s\n\x05Order\x12-\n\x0c\x61lgorithm_id\x18\x01 \x01(\x0b\x32\x17.supervisor.AlgorithmId\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x0e\n\x06volume\x18\x03 \x01(\x01\x12\r\n\x05limit\x18\x04 \x01(\x01\x12\x0c\n\x04stop\x18\x05 \x01(\x01\"\x13\n\x11OrderConfirmation\"z\n\tPortfolio\x12\x31\n\x06stocks\x18\x01 \x03(\x0b\x32!.supervisor.Portfolio.StocksEntry\x12\x0b\n\x03usd\x18\x02 \x01(\x01\x1a-\n\x0bStocksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"A\n\rAlgorithmSpec\x12#\n\x02id\x18\x01 \x01(\x0b\x32\x17.supervisor.AlgorithmId\x12\x0b\n\x03url\x18\x02 \x01(\t\"\xb1\x01\n\x18SynchronousDailySimInput\x12)\n\x05start\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\noutput_dir\x18\x03 \x01(\t\x12-\n\nalgorithms\x18\x04 \x03(\x0b\x32\x19.supervisor.AlgorithmSpec\"\x1b\n\x19SynchronousDailySimOutput\"\x0c\n\nAbortInput\"\r\n\x0b\x41\x62ortOutput\"\x15\n\x13\x44oneTradingResponse2\xfd\x02\n\nSupervisor\x12@\n\nPlaceOrder\x12\x11.supervisor.Order\x1a\x1d.supervisor.OrderConfirmation\"\x00\x12@\n\x0cGetPortfolio\x12\x17.supervisor.AlgorithmId\x1a\x15.supervisor.Portfolio\"\x00\x12I\n\x0b\x44oneTrading\x12\x17.supervisor.AlgorithmId\x1a\x1f.supervisor.DoneTradingResponse\"\x00\x12\x64\n\x13SynchronousDailySim\x12$.supervisor.SynchronousDailySimInput\x1a%.supervisor.SynchronousDailySimOutput\"\x00\x12:\n\x05\x41\x62ort\x12\x16.supervisor.AbortInput\x1a\x17.supervisor.AbortOutput\"\x00\x42:Z8github.com/d-sparks/gravy/supervisor/proto;supervisor_pbb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ALGORITHMID = _descriptor.Descriptor(
  name='AlgorithmId',
  full_name='supervisor.AlgorithmId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm_id', full_name='supervisor.AlgorithmId.algorithm_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=100,
)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='supervisor.Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm_id', full_name='supervisor.Order.algorithm_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ticker', full_name='supervisor.Order.ticker', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='supervisor.Order.volume', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='supervisor.Order.limit', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stop', full_name='supervisor.Order.stop', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=217,
)


_ORDERCONFIRMATION = _descriptor.Descriptor(
  name='OrderConfirmation',
  full_name='supervisor.OrderConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=238,
)


_PORTFOLIO_STOCKSENTRY = _descriptor.Descriptor(
  name='StocksEntry',
  full_name='supervisor.Portfolio.StocksEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='supervisor.Portfolio.StocksEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='supervisor.Portfolio.StocksEntry.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=362,
)

_PORTFOLIO = _descriptor.Descriptor(
  name='Portfolio',
  full_name='supervisor.Portfolio',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stocks', full_name='supervisor.Portfolio.stocks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usd', full_name='supervisor.Portfolio.usd', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PORTFOLIO_STOCKSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=362,
)


_ALGORITHMSPEC = _descriptor.Descriptor(
  name='AlgorithmSpec',
  full_name='supervisor.AlgorithmSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='supervisor.AlgorithmSpec.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='url', full_name='supervisor.AlgorithmSpec.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=429,
)


_SYNCHRONOUSDAILYSIMINPUT = _descriptor.Descriptor(
  name='SynchronousDailySimInput',
  full_name='supervisor.SynchronousDailySimInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='supervisor.SynchronousDailySimInput.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end', full_name='supervisor.SynchronousDailySimInput.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='output_dir', full_name='supervisor.SynchronousDailySimInput.output_dir', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithms', full_name='supervisor.SynchronousDailySimInput.algorithms', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=432,
  serialized_end=609,
)


_SYNCHRONOUSDAILYSIMOUTPUT = _descriptor.Descriptor(
  name='SynchronousDailySimOutput',
  full_name='supervisor.SynchronousDailySimOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=611,
  serialized_end=638,
)


_ABORTINPUT = _descriptor.Descriptor(
  name='AbortInput',
  full_name='supervisor.AbortInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=640,
  serialized_end=652,
)


_ABORTOUTPUT = _descriptor.Descriptor(
  name='AbortOutput',
  full_name='supervisor.AbortOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=667,
)


_DONETRADINGRESPONSE = _descriptor.Descriptor(
  name='DoneTradingResponse',
  full_name='supervisor.DoneTradingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=669,
  serialized_end=690,
)

_ORDER.fields_by_name['algorithm_id'].message_type = _ALGORITHMID
_PORTFOLIO_STOCKSENTRY.containing_type = _PORTFOLIO
_PORTFOLIO.fields_by_name['stocks'].message_type = _PORTFOLIO_STOCKSENTRY
_ALGORITHMSPEC.fields_by_name['id'].message_type = _ALGORITHMID
_SYNCHRONOUSDAILYSIMINPUT.fields_by_name['start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SYNCHRONOUSDAILYSIMINPUT.fields_by_name['end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SYNCHRONOUSDAILYSIMINPUT.fields_by_name['algorithms'].message_type = _ALGORITHMSPEC
DESCRIPTOR.message_types_by_name['AlgorithmId'] = _ALGORITHMID
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
DESCRIPTOR.message_types_by_name['OrderConfirmation'] = _ORDERCONFIRMATION
DESCRIPTOR.message_types_by_name['Portfolio'] = _PORTFOLIO
DESCRIPTOR.message_types_by_name['AlgorithmSpec'] = _ALGORITHMSPEC
DESCRIPTOR.message_types_by_name['SynchronousDailySimInput'] = _SYNCHRONOUSDAILYSIMINPUT
DESCRIPTOR.message_types_by_name['SynchronousDailySimOutput'] = _SYNCHRONOUSDAILYSIMOUTPUT
DESCRIPTOR.message_types_by_name['AbortInput'] = _ABORTINPUT
DESCRIPTOR.message_types_by_name['AbortOutput'] = _ABORTOUTPUT
DESCRIPTOR.message_types_by_name['DoneTradingResponse'] = _DONETRADINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlgorithmId = _reflection.GeneratedProtocolMessageType('AlgorithmId', (_message.Message,), {
  'DESCRIPTOR' : _ALGORITHMID,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.AlgorithmId)
  })
_sym_db.RegisterMessage(AlgorithmId)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.Order)
  })
_sym_db.RegisterMessage(Order)

OrderConfirmation = _reflection.GeneratedProtocolMessageType('OrderConfirmation', (_message.Message,), {
  'DESCRIPTOR' : _ORDERCONFIRMATION,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.OrderConfirmation)
  })
_sym_db.RegisterMessage(OrderConfirmation)

Portfolio = _reflection.GeneratedProtocolMessageType('Portfolio', (_message.Message,), {

  'StocksEntry' : _reflection.GeneratedProtocolMessageType('StocksEntry', (_message.Message,), {
    'DESCRIPTOR' : _PORTFOLIO_STOCKSENTRY,
    '__module__' : 'supervisor_pb2'
    # @@protoc_insertion_point(class_scope:supervisor.Portfolio.StocksEntry)
    })
  ,
  'DESCRIPTOR' : _PORTFOLIO,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.Portfolio)
  })
_sym_db.RegisterMessage(Portfolio)
_sym_db.RegisterMessage(Portfolio.StocksEntry)

AlgorithmSpec = _reflection.GeneratedProtocolMessageType('AlgorithmSpec', (_message.Message,), {
  'DESCRIPTOR' : _ALGORITHMSPEC,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.AlgorithmSpec)
  })
_sym_db.RegisterMessage(AlgorithmSpec)

SynchronousDailySimInput = _reflection.GeneratedProtocolMessageType('SynchronousDailySimInput', (_message.Message,), {
  'DESCRIPTOR' : _SYNCHRONOUSDAILYSIMINPUT,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.SynchronousDailySimInput)
  })
_sym_db.RegisterMessage(SynchronousDailySimInput)

SynchronousDailySimOutput = _reflection.GeneratedProtocolMessageType('SynchronousDailySimOutput', (_message.Message,), {
  'DESCRIPTOR' : _SYNCHRONOUSDAILYSIMOUTPUT,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.SynchronousDailySimOutput)
  })
_sym_db.RegisterMessage(SynchronousDailySimOutput)

AbortInput = _reflection.GeneratedProtocolMessageType('AbortInput', (_message.Message,), {
  'DESCRIPTOR' : _ABORTINPUT,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.AbortInput)
  })
_sym_db.RegisterMessage(AbortInput)

AbortOutput = _reflection.GeneratedProtocolMessageType('AbortOutput', (_message.Message,), {
  'DESCRIPTOR' : _ABORTOUTPUT,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.AbortOutput)
  })
_sym_db.RegisterMessage(AbortOutput)

DoneTradingResponse = _reflection.GeneratedProtocolMessageType('DoneTradingResponse', (_message.Message,), {
  'DESCRIPTOR' : _DONETRADINGRESPONSE,
  '__module__' : 'supervisor_pb2'
  # @@protoc_insertion_point(class_scope:supervisor.DoneTradingResponse)
  })
_sym_db.RegisterMessage(DoneTradingResponse)


DESCRIPTOR._options = None
_PORTFOLIO_STOCKSENTRY._options = None

_SUPERVISOR = _descriptor.ServiceDescriptor(
  name='Supervisor',
  full_name='supervisor.Supervisor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=693,
  serialized_end=1074,
  methods=[
  _descriptor.MethodDescriptor(
    name='PlaceOrder',
    full_name='supervisor.Supervisor.PlaceOrder',
    index=0,
    containing_service=None,
    input_type=_ORDER,
    output_type=_ORDERCONFIRMATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPortfolio',
    full_name='supervisor.Supervisor.GetPortfolio',
    index=1,
    containing_service=None,
    input_type=_ALGORITHMID,
    output_type=_PORTFOLIO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DoneTrading',
    full_name='supervisor.Supervisor.DoneTrading',
    index=2,
    containing_service=None,
    input_type=_ALGORITHMID,
    output_type=_DONETRADINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SynchronousDailySim',
    full_name='supervisor.Supervisor.SynchronousDailySim',
    index=3,
    containing_service=None,
    input_type=_SYNCHRONOUSDAILYSIMINPUT,
    output_type=_SYNCHRONOUSDAILYSIMOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Abort',
    full_name='supervisor.Supervisor.Abort',
    index=4,
    containing_service=None,
    input_type=_ABORTINPUT,
    output_type=_ABORTOUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SUPERVISOR)

DESCRIPTOR.services_by_name['Supervisor'] = _SUPERVISOR

# @@protoc_insertion_point(module_scope)
