{
 "title": "GravyTimescaleOutput",
 "time": { "from": "2006-03-03T21:02:56.642Z", "to": "2008-11-22T14:53:30.654Z" },
 "templating": {
  "list": [
   { "name": "run_timestamp", "label": "Run timstamp", "query": "1619279033" },
   { "name": "main_strategy", "label": "Main strategy", "query": "correlatedpairs" },
   { "name": "strategy_1", "label": "Baseline algorithm 1", "query": "buyandhold" },
   { "name": "strategy_2", "label": "Baseline algorithm 2", "query": "buyspy" }
  ]
 },
 "panels": [
  {
   "title": "Portfolio Values",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_portfolio_value,\n  ${strategy_1}_portfolio_value,\n  ${strategy_2}_portfolio_value\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Alpha",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_alpha_252,\n  ${strategy_1}_alpha_252,\n  ${strategy_2}_alpha_252\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Beta",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_beta_252,\n  ${strategy_1}_beta_252,\n  ${strategy_2}_beta_252\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Significant Holdings",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_significant_holdings\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Capital Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (${main_strategy}_portfolio_value - ${main_strategy}_usd) / ${main_strategy}_portfolio_value\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "In position vs out of position",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_usd / ${main_strategy}_portfolio_value AS \"USD fraction\",\n  ${main_strategy}_pos_value / ${main_strategy}_portfolio_value AS \"Position fraction\",\n  ${main_strategy}_oop_value / ${main_strategy}_portfolio_value AS \"Out of position fraction\"\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Opening / closing positions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_num_opening_positions AS \"Num opening positions\",\n  ${main_strategy}_num_closing_positions AS \"Num closing positions\"\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Buys and sells",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_buys_value / ${main_strategy}_portfolio_value AS \"Buys\",\n  ${main_strategy}_sells_value / ${main_strategy}_portfolio_value AS \"Sells\"\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Closing position returns",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_closing_pos_return_min AS \"Min\",\n  ${main_strategy}_closing_pos_return_mean AS \"Mean\",\n  ${main_strategy}_closing_pos_return_max AS \"Max\"\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Out of position distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_oop_deviation_10p AS \"10p\",\n  ${main_strategy}_oop_deviation_25p AS \"25p\",\n  ${main_strategy}_oop_deviation_50p AS \"50p\",\n  ${main_strategy}_oop_deviation_75p AS \"75p\",\n  ${main_strategy}_oop_deviation_90p AS \"90p\"\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Num bogus closing positions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ${main_strategy}_closing_num_bogus AS \"Num\"\nFROM timescaleout$run_timestamp\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}